Page/AddPage
christophschmitz/mastery pull request #49
Opened 2021-09-22 15:27 UTC by christophschmitz

Hello, 
I added the AddPage!

- Add category map
- Update Routes in App tsx
- Implement Addpage
- Styling AddPage

resolves: #24

2021-09-23 08:45 UTC, marwinburesch commented on src/app/hooks/useAllSkills.ts
> +export default function useAllSkills(): {
Couldn't it just be named `useSkills`? I could also imagine rewriting this hook later to return either a specific or all skills :)

2021-09-23 08:45 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +  });
```suggestion
  const allCategorys = skills?.map((skill) => {
    const {title, imageSrc, description, category } = skill
    return { title, imageSrc, description,category };
  });
```

2021-09-23 08:45 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +    <>
These are redundant since you already return one top level element :)

2021-09-23 08:45 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +          <Header
Isn't this a header already? If not, it should be.

2021-09-23 08:45 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +        <div>
What's this for?

2021-09-23 15:59 UTC, phlgr requested changes
Your deployment seems to fail. Please look into it and feel free to contact me if you need help.

2021-09-23 15:59 UTC, phlgr commented on src/app/App.tsx
> +        <Route path="/"></Route>
These are not needed yet

2021-09-23 16:05 UTC, christophschmitz commented
> Your deployment seems to fail. Please look into it and feel free to contact me if you need help.

Hi, its working on my side. Just use the link in the description. [Deployment](https://mastery-page-addpage-bz497ymso.herokuapp.com/add)

2021-09-24 08:25 UTC, marwinburesch reviewed
nice

2021-09-24 08:25 UTC, marwinburesch commented on src/app/components/Card/Card.stories.tsx
> +    progress={0}
You don't need curly brackets for strings and numbers

2021-09-24 08:25 UTC, marwinburesch commented on src/app/hooks/useLocalStorageSkills.ts
> +export default function useSkills(): {
Filenames should correspond with default export names or vice versa

2021-09-24 08:25 UTC, marwinburesch commented on src/app/hooks/useLocalStorageSkills.ts
> +  function addOnClick(skill: Skill) {
`addSkill`?

2021-09-24 08:25 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +                onClick={() => handleAddOnClick(skills)}
Just some light name changes could make this read like: `onAddClick={() => addSkill(skill)}`

2021-09-24 08:25 UTC, marwinburesch commented on src/app/pages/AddPage/AddPage.tsx
> +          filteredSkills.map((skills) => {
```suggestion
          filteredSkills.map((skill) => {
```

2021-09-24 09:09 UTC, merged